owner: Tubnom
repo: tubnet-uptime

sites:
  - name: TubNet Java (prod)
    url: prod.tubnet.gg
    check: "tcp-ping"
    port: 25565
    
  - name: TubNet Java (lunar)
    url: lunar.tubnet.gg
    check: "tcp-ping"
    port: 25565
    
  - name: TubNet Java (thru)
    url: thru.tubnet.gg
    check: "tcp-ping"
    port: 25565
    
  - name: TubNet Java (mc)
    url: mc.tubnet.gg
    check: "tcp-ping"
    port: 25565
    
  - name: TubNet Events
    url: 5.161.155.38
    check: "tcp-ping"
    port: 25565
    
  - name: TubNet Forums
    url: https://forums.tubnet.gg/
    expectedStatusCodes:
      - 403
    
  - name: CDN (S3 Bucket)
    url: https://cdn.tubnet.gg/minecraft-resourcepack/TubPack-production.zip
    
  - name: TubNet Rewards (Frontend)
    url: https://rewards.tubnet.gg
  
  - name: TubNet Rewards (Backend)
    url: https://reward.prd.svc.tubnet.io/
    expectedStatusCodes:
      - 500
  
  - name: TubNet Proxmox (EB)
    url: https://eb.clmgr.tubnet.io
    
  - name: TubNet Proxmox (FS)
    url: https://fs.clmgr.tubnet.io
    
  - name: Creg (?)
    url: https://creg.tubnet.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: /tubnet-uptime
  logoUrl: https://avatars.githubusercontent.com/u/102187236?s=200&v=4
  name: TubNet Community
  introTitle: "TubNet Status"
  introMessage: "This website tracks TubNet's servers and checks when they are down."
  navbar:
    - title: Status
      href: /tubnet-uptime
    - title: Tubble
      href: https://forums.tubnet.gg/
    - title: Discord
      href: https://dsc.gg/apricotfarmer11

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
