# Change these first
owner: Tubnom
repo: tubnet-uptime

sites:
  - name: Tubble
    url: https://forums.tubnet.gg
    
  - name: Content Delivery Network (S3 Bucket)
    url: https://cdn.tubnet.gg
    
  - name: TubNet Rewards (Frontend)
    url: https://rewards.tubnet.gg
  
  - name: TubNet Rewards (Backend)
    url: https://reward.prd.svc.tubnet.io
  
  - name: TubNet Proxmox (EB)
    url: https://eb.clmgr.tubnet.io
    
  - name: TubNet Proxmox (FS)
    url: https://fs.clmgr.tubnet.io
    
  - name: Creg (?)
    url: https://creg.tubnet.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /tubnet-uptime
  logoUrl: https://avatars.githubusercontent.com/u/102187236?s=200&v=4
  name: Tubnom
  introTitle: "TubNet Status"
  introMessage: "This website tracks TubNet's servers and checks when they are down."
  navbar:
    - title: Status
      href: /
    - title: Tubble
      href: https://forums.tubnet.gg/
    - title: Discord
      href: https://dsc.gg/apricotfarmer11

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
